### PR TITLE
Release/0.1.0

### PR DESCRIPTION
**Pull request by mahdi943**
Provide Blockly part only of tool 
modifying update.js and index.html

### CODE REVIEW

**Comment by turalnovruzov** [comment]
This is a bad idea. **Do not merge this branch to master**

**Comment by cemaly** [comment]
Do we have an update on this issue?

**Comment by cemaly** [comment]
Can you tell us why do you think this is a bad idea and what needs to be changed?

**Comment by turalnovruzov** [comment]
I talked with Mahdi, and we think it is alright to merge. It was a long term issue, but we will be able to fix it. If you want to I can explain it to you in a meeting

**Review by turalnovruzov — APPROVED** [review]
Everything seems alright.

**Pull request merged**
