### PR TITLE
Feature/ui

### PR DESCRIPTION
**Pull request by mahdi943**
I added some buttons and also functions related them.
I also changed the location of buttons so I edited css files

Path issue still is a problem, in windows  should be \ , but in docker / 
So I couldn't run bdd because step-definition.py couldn't be found, but I am sure it works in doker and I will test again after merging in docker.

### CODE REVIEW

**Comment by turalnovruzov** [comment]
What do you mean by it should be \ on windows. My file server only works with /. Even if the operating system is windows, the slashes will be /.

Can you elaborate if you anything else?

**Comment by mahdi943** [comment]
I have the format below in my machine when I want to run a bdd file:
 Calculator\bdd\open.feature

I parse this string to go under: Calculator\bdd

and read: Calculator\bdd\step-definition.py

**Comment by turalnovruzov** [comment]
I know that on your machine it is \. However, you are getting that path by using my file-server.js, which only works with forward slashes (/). So even if your machine is Windows, the code still uses the file-server.js which in turn uses the file-server API, which in turn uses only (/), during communication. So this is not an issue.

I developed the file-server API and file-server.js so that they are platform-independent. So no matter which os you are using, please only use / with the file-server.js.

Please let me know if there is still an issue. If not I will merge the pull request.

**Comment by mahdi943** [comment]
You can merge it. I will show you the problem tomorrow. today we had
problem with \\ in docker. I solve the problem by changing to /.

**Comment by turalnovruzov** [comment]
Is this branch done with? If yes, I will delete it and you can create a new one for the next feature you will work on.

**Comment by mahdi943** [comment]
I am working on it.

**Pull request merged**
